services:

  app:
    build:
      context: ./docker/php
    container_name: ijaraga_app
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: ijaraga_nginx
    ports:
      - "8100:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:16-alpine
    container_name: ijaraga_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ijaraga
      POSTGRES_USER: ijaraga
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

  frontend:
    build: ./frontend
    container_name: ijaraga_frontend
    ports:
      - "1173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: